In [151]:
import pandas as pd

name = 'p-zaparoan'
df = pd.read_csv(f'{name}.csv')
#df = df.drop('index', axis=1)
df = df.dropna(subset=['FORM'])
df['Language'] = 'Proto-Zaparoan'
df['Glottocode'] = 'zapa1251'
df['Family'] = 'Zaparoan'
display(df.head())

             Gloss      FORM        Language Glottocode    Family
0        bee, wasp  *ahapaka  Proto-Zaparoan   zapa1251  Zaparoan
1            stick    *amaka  Proto-Zaparoan   zapa1251  Zaparoan
2          to kill      *amo  Proto-Zaparoan   zapa1251  Zaparoan
3  woman's sibling     *ana-  Proto-Zaparoan   zapa1251  Zaparoan
4     cloud, smoke  *anahaka  Proto-Zaparoan   zapa1251  Zaparoan

In [152]:
s_gloss = df['Gloss'].str.replace('"', '').str.split(',').explode()
s_gloss.name = 'Gloss'
df = df.drop('Gloss', axis=1).join(s_gloss)

# Remove text within parentheses from the 'Gloss' column
df['Gloss'] = df['Gloss'].str.replace(r'\(.*?\)', '', regex=True).str.strip()

display(df.head())

       FORM        Language Glottocode    Family            Gloss
0  *ahapaka  Proto-Zaparoan   zapa1251  Zaparoan              bee
0  *ahapaka  Proto-Zaparoan   zapa1251  Zaparoan             wasp
1    *amaka  Proto-Zaparoan   zapa1251  Zaparoan            stick
2      *amo  Proto-Zaparoan   zapa1251  Zaparoan          to kill
3     *ana-  Proto-Zaparoan   zapa1251  Zaparoan  woman's sibling

In [153]:
# Display columns of df right before the line causing the error
print("Columns of df before processing 'Phonemicized Form':")
print(df.columns)

s_form = df['FORM'].str.split(r'[~,]').explode()
s_form.name = 'FORM'
df = df.drop('FORM', axis=1).join(s_form)

# Remove unwanted characters from the FORM column
df['FORM'] = df['FORM'].str.replace(r'[*\-\(\)]', '', regex=True)

display(df.head())

Columns of df before processing 'Phonemicized Form':
Index(['FORM', 'Language', 'Glottocode', 'Family', 'Gloss'], dtype='object')

         Language Glottocode    Family  Gloss     FORM
0  Proto-Zaparoan   zapa1251  Zaparoan    bee  ahapaka
0  Proto-Zaparoan   zapa1251  Zaparoan    bee  ahapaka
0  Proto-Zaparoan   zapa1251  Zaparoan   wasp  ahapaka
0  Proto-Zaparoan   zapa1251  Zaparoan   wasp  ahapaka
1  Proto-Zaparoan   zapa1251  Zaparoan  stick    amaka

In [154]:
#df = df[['Gloss', 'Language', 'Glottocode', 'Family', 'Phonemicized Form']]
df = df[['Gloss', 'Language', 'Glottocode', 'Family', 'FORM']]

df.to_csv(f'{name}.tsv', sep='\t', index=False, quoting=3)