In [41]:
import pandas as pd

df = pd.read_csv('/content/basic_vocabulary_full.csv')
df = df.reset_index()
cols = df.columns.tolist()
cols = cols[-1:] + cols[:-1]
df = df[cols]
columns_to_drop = ['Source', 'Language', 'ID', 'GLOSS', 'Orthographic Form', 'Phonemicized Form', 'Gloss as in Source', 'Etymology Code', 'Proto-Language', 'Loan Source', 'Wanderwort Status', 'Etyma Set', 'Etymology Notes', 'General Notes']
df = df.drop(columns=columns_to_drop)
display(df.head())

        index      Family Gloss Link Proto-Form
0  Araucanian  Mapudungun      above      wente
1  Araucanian  Mapudungun        and        NaN
2  Araucanian  Mapudungun        ash   ṭ͡ʀufken
3  Araucanian  Mapudungun         at        NaN
4  Araucanian  Mapudungun       back       furi

In [42]:
empty_cells_per_column = df.isnull().sum()
print("Number of empty cells per column:")
print(empty_cells_per_column)

Number of empty cells per column:
index            0
Family           0
Gloss Link       0
Proto-Form    5704
dtype: int64

In [43]:
df = df.dropna(subset=['Proto-Form'])
display(df.head())

        index      Family Gloss Link Proto-Form
0  Araucanian  Mapudungun      above      wente
2  Araucanian  Mapudungun        ash   ṭ͡ʀufken
4  Araucanian  Mapudungun       back       furi
5  Araucanian  Mapudungun        bad       weθa
6  Araucanian  Mapudungun      belly     pɨṭ͡ʀa

In [44]:
df_split = df['Gloss Link'].str.split('/', expand=True).stack().reset_index(level=1, drop=True).to_frame('Gloss Link')
df_split = df_split.merge(df.drop('Gloss Link', axis=1), left_index=True, right_index=True, how='left')
# Reorder columns to match the original DataFrame
original_cols = df.columns.tolist()
df_split = df_split[original_cols]
display(df_split.head())

        index      Family Gloss Link Proto-Form
0  Araucanian  Mapudungun      above      wente
2  Araucanian  Mapudungun        ash   ṭ͡ʀufken
4  Araucanian  Mapudungun       back       furi
5  Araucanian  Mapudungun        bad       weθa
6  Araucanian  Mapudungun      belly     pɨṭ͡ʀa

In [52]:
df_split['Proto-Form'] = df_split['Proto-Form'].str.replace(r" \(.+\)(?=[,;])", "", regex=True)
display(df_split.head())

        index      Family Gloss Link Proto-Form
0  Araucanian  Mapudungun      above      wente
2  Araucanian  Mapudungun        ash   ṭ͡ʀufken
4  Araucanian  Mapudungun       back       furi
5  Araucanian  Mapudungun        bad       weθa
6  Araucanian  Mapudungun      belly     pɨṭ͡ʀa

In [53]:
df_split['Proto-Form'] = df_split['Proto-Form'].str.replace(r" \(.+\)", "", regex=True)
display(df_split.head())

        index      Family Gloss Link Proto-Form
0  Araucanian  Mapudungun      above      wente
2  Araucanian  Mapudungun        ash   ṭ͡ʀufken
4  Araucanian  Mapudungun       back       furi
5  Araucanian  Mapudungun        bad       weθa
6  Araucanian  Mapudungun      belly     pɨṭ͡ʀa

In [54]:
df_split['Proto-Form'] = df_split['Proto-Form'].str.replace(r" \[.+\](?=[,;])", "", regex=True)
display(df_split.head())

        index      Family Gloss Link Proto-Form
0  Araucanian  Mapudungun      above      wente
2  Araucanian  Mapudungun        ash   ṭ͡ʀufken
4  Araucanian  Mapudungun       back       furi
5  Araucanian  Mapudungun        bad       weθa
6  Araucanian  Mapudungun      belly     pɨṭ͡ʀa

In [55]:
df_split['Proto-Form'] = df_split['Proto-Form'].str.replace(r" \[.+\]", "", regex=True)
display(df_split.head())

        index      Family Gloss Link Proto-Form
0  Araucanian  Mapudungun      above      wente
2  Araucanian  Mapudungun        ash   ṭ͡ʀufken
4  Araucanian  Mapudungun       back       furi
5  Araucanian  Mapudungun        bad       weθa
6  Araucanian  Mapudungun      belly     pɨṭ͡ʀa

In [57]:
df_split.to_csv('cleaned_basic_vocabulary.csv', index=False)